### PR TITLE
Adds a new endpoint to receive a list of all of a users 

### PR DESCRIPTION
**Pull request by matthewgrossman**
### What

Changes some existing code for reservation management within use. Now should be easier to parse client side.

New endpoint and model code will allow you to get all the spots for a given user.

### CODE REVIEW

**Comment by matthewgrossman** [comment]
@kenzshelley @nickcharles

**Comment by kenzshelley** [comment]
lgtm

**Comment by kenzshelley** [comment]
jk, ❌ 👍,  revert.

**Comment by matthewgrossman** [comment]
this project was so much fun

**Comment by matthewgrossman** [comment]
nostalgia

**Comment by matthewgrossman** [comment]
feels

**Pull request merged**
